orbs:
  react: "thefrontside/react@0.2.0"
  codecov: codecov/codecov@1.0.5
version: 2.1
workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - coverage:
          requires:
            - react/install
jobs:
  coverage:
    executor: react/default
    steps:
      - attach_workspace:
          at: ~/
      - react/coverage
      - store_artifacts:
          path: ./artifacts
      - codecov/upload:
          file: artifacts/coverage/coverage-final.json
